#!/bin/bash

# imports
. scripts/utils.sh

function createManufacturerOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/manufacturer.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-manufacturer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-manufacturer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy manufacturer's CA cert to manufacturer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy manufacturer's CA cert to manufacturer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/tlsca/tlsca.manufacturer.supplychain.com-cert.pem"

  # Copy manufacturer's CA cert to manufacturer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/ca/ca.manufacturer.supplychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-manufacturer --id.name manufactureradmin --id.secret manufactureradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/msp" --csr.hosts peer0.manufacturer.supplychain.com --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.manufacturer.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/peers/peer0.manufacturer.supplychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/users/User1@manufacturer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/users/User1@manufacturer.supplychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://manufactureradmin:manufactureradminpw@localhost:7054 --caname ca-manufacturer -M "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/users/Admin@manufacturer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/manufacturerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/manufacturer.supplychain.com/users/Admin@manufacturer.supplychain.com/msp/config.yaml"
}

function createRetailerOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/retailer.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/retailer.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-retailer --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-retailer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy retailer's CA cert to retailer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy retailer's CA cert to retailer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/tlsca/tlsca.retailer.supplychain.com-cert.pem"

  # Copy retailer's CA cert to retailer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/ca/ca.retailer.supplychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-retailer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-retailer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-retailer --id.name retaileradmin --id.secret retaileradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/msp" --csr.hosts peer0.retailer.supplychain.com --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.retailer.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/peers/peer0.retailer.supplychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/users/User1@retailer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/users/User1@retailer.supplychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://retaileradmin:retaileradminpw@localhost:8054 --caname ca-retailer -M "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/users/Admin@retailer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/retailerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/retailer.supplychain.com/users/Admin@retailer.supplychain.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/orderer.supplychain.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/orderer.supplychain.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/msp/tlscacerts/tlsca.orderer.supplychain.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/tlsca/tlsca.orderer.supplychain.com-cert.pem"

  infoln "Registering orderer1"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer1 --id.secret orderer1pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer1:orderer1pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/msp" --csr.hosts orderer1.orderer.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates"
  set -x
  fabric-ca-client enroll -u https://orderer1:orderer1pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls" --enrollment.profile tls --csr.hosts orderer1.orderer.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/orderers/orderer1.orderer.supplychain.com/msp/tlscacerts/tlsca.orderer.supplychain.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/users/Admin@orderer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/orderer.supplychain.com/users/Admin@orderer.supplychain.com/msp/config.yaml"
}

function createCustomerOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/customer.supplychain.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/customer.supplychain.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-customer --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-customer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-customer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-customer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-customer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/customer.supplychain.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy customer's CA cert to customer's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/customer.supplychain.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/customer.supplychain.com/msp/tlscacerts/ca.crt"

  # Copy customer's CA cert to customer's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/customer.supplychain.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/customer.supplychain.com/tlsca/tlsca.customer.supplychain.com-cert.pem"

  # Copy customer's CA cert to customer's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/customer.supplychain.com/ca"
  cp "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem" "${PWD}/organizations/peerOrganizations/customer.supplychain.com/ca/ca.customer.supplychain.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-customer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-customer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-customer --id.name customeradmin --id.secret customeradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/msp" --csr.hosts peer0.customer.supplychain.com --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/customer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:10054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls" --enrollment.profile tls --csr.hosts peer0.customer.supplychain.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/customer.supplychain.com/peers/peer0.customer.supplychain.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:10054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.supplychain.com/users/User1@customer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/customer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/customer.supplychain.com/users/User1@customer.supplychain.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://customeradmin:customeradminpw@localhost:10054 --caname ca-customer -M "${PWD}/organizations/peerOrganizations/customer.supplychain.com/users/Admin@customer.supplychain.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/customerOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/customer.supplychain.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/customer.supplychain.com/users/Admin@customer.supplychain.com/msp/config.yaml"
}
